# Generated by Django 4.1.2 on 2022-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
